apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflow-engine
  name: workflow-engine
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: workflow-engine